export const OAUTH2 = 'OAUTH2';
export const OAUTH2_PENDING = 'OAUTH2_PENDING';
export const OAUTH2_FULFILLED = 'OAUTH2_FULFILLED';
export const OAUTH2_REJECTED = 'OAUTH2_REJECTED';

export const OAUTH2_CODE_TOKEN = 'OAUTH2_CODE_TOKEN';
export const OAUTH2_CODE_TOKEN_PENDING = 'OAUTH2_CODE_TOKEN_PENDING';
export const OAUTH2_CODE_TOKEN_FULFILLED = 'OAUTH2_CODE_TOKEN_FULFILLED';
export const OAUTH2_CODE_TOKEN_REJECTED = 'OAUTH2_CODE_TOKEN_REJECTED';

export const OAUTH2_LOGOUT = 'OAUTH2_LOGOUT';
